name: "lint, build & test"
on: # rebuild any PRs and main branch changes (mirror few typescript-action conventions)
  pull_request:
  push:
jobs:
  build-test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: setup node
      with:
        node-version: '13.x'

    - name: "install"
      run: npm ci

    - name: "build"
      run: npm run build

    - name: "test"
      run: npm run test

    - name: "check for uncommitted changes"
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "found changed files after build, building and commiting again" \
            && exit 1)

    - name: "archive lib when diff"
      if: success()
      uses:
           github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: ${{github.head_ref}}
        commit-message: 'build action'
        files: lib
        name: Build action bot
        email: buildaction@bot.bot



