name: "test -> build -> update lib if needed"
on:
  push:
jobs:
  build-test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: setup node
      with:
        node-version: '13.x'

    - name: "install"
      run: npm ci --production

    - name: "test"
      run: npm run test

    - name: "build"
      run: npm run build

    - name: "check if build has changed"
      id: has-changes
      run: echo ::set-output name=LIB_DIFF::$(git diff  --stat -- . ':!node_modules')

  push-build:
    needs: build-test
    if: needs.build-test.outputs.LIB_DIFF
    runs-on: ubuntu-16.04
    steps:
    - name: "archive lib when diff"
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'build action'
        files: lib
        name: Build action bot
        email: buildaction@bot.bot
